### ISSUE TITLE
Add an ability to automatically extract code from the code base into reStructuredText for a macro

### ISSUE THREAD

**Issue by jburz2001** [vnvlabs/vnv#3]
Provide the ability to automatically convert source code into reStructuredText that can be included in a macro.

For instance, implement a way to take include code from a function in the comment above INJECTION_TEST:

Code snippet;
```
int add(int a, int b) { return a + b; }
```

reStructuredText:
```
.. code:: cpp

    int add(int a, int b) { return a + b; }
```

**Comment by jburz2001** [comment]
It likely depends on how its implemented, but it would likely be nice to let the user specify which coding language they want the reStructuredText to be in when they instruct VnV to extract code.

**Comment by beon9273** [comment]
What about some living like this.

    /**
     The code was
      .. vnv-code-block:: cb1
    */
    INJECTION_POINT(...)
    .......

INJECTION_CODEBLOCK_START(cb1)
<code to render>
INJECTION_CODEBLOCK_END(cb1)

....

**Comment by beon9273** [comment]
We could also allow passing the function name I stead of a marked code block... that's doable as well but a little harder

**Comment by jburz2001** [comment]
I do like the idea of referencing a code block with `cb#` for code blocks. However, keeping track of the number may unfortunately be a bit difficult for large codebases. For instance, the following header file for the matplotlib-cpp library has 2986 lines of code: [https://github.com/lava/matplotlib-cpp/blob/master/matplotlibcpp.h](https://github.com/lava/matplotlib-cpp/blob/master/matplotlibcpp.h). This example may be an "edge case", but users may have some troubles once they have 20+ code blocks.

I think that having the method of
```
/**

INJECTION_CODEBLOCK_START(cb1)
<code to render>
INJECTION_CODEBLOCK_END(cb1)
....
```
should remain, but it would be nice to have extend its capabilities so that the user does not need to keep track of numbers. Enabling the user to input an arbitrary string instead of just a number to identify a code block would help disambiguate the code blocks. For instance, a user can use `cb_populatePhaseVector` and `cb_writeToFile` instead of `cb3` and `cb27`. This may also satisfy the "passing the function name" method since the user could put `cb_function_readCsv` to reference a `readCsv` function.

**Comment by beon9273** [comment]
Agreed. An arbitrary sting makes sense. I will probably add in the package
name as well so it's consistent with all the other INJECTION macros.

In the larger scheme of things this Is a kind of "static" data collection
(whereas the engine class provides dynamic runtime data collection).

I could see benefit in being able to reference arbitrary "static" data
inside comment blocks. I.e.


/**

The version is :vnv:`static.version`
The code was

.. vnv-code:: static.cobeblockname

**/

INJECTION_STATIC(version,10)

INJECTION_CODE(codeblockname)
...
INJECTION_CODE_END(codeblockname)

...


This would provide some resilience in terms of not hard coing values into
the comments
