### ISSUE TITLE
Possible typo in Injection.h macro?

### ISSUE THREAD

**Issue by jburz2001** [vnvlabs/vnv#7]
@beon9273 
Am I correct that the ) after STAGE should be removed in the code that is substituted in for INJECTION_LOOP_ITER_D ?
path: _/vnv/injection/include/c-interfaces/points/Injection.h_

```
#  define INJECTION_LOOP_ITER(PNAME, NAME, STAGE) \
    _VnV_injectionPoint_loop(VNV_STR(PNAME), VNV_STR(NAME), VNV_STR(STAGE), __FILE__, __LINE__);

//FIXME remove ) after STAGE ?
#  define INJECTION_LOOP_ITER_D(PNAME, NAME, STAGE) \
    _VnV_injectionPoint_loop(VNV_STR(PNAME), VNV_STR(NAME), STAGE), __FILE__, __LINE__);
```

**Comment by beon9273** [comment]
Yea. You are right. We must not use that macro in any of the examples
anywhere I guess

Good catch

**Comment by jburz2001** [comment]
Well, couldn't we just fix the bug? I'm fine with doing it, I just wanted to check with you beforehand

**Comment by beon9273** [comment]
Yip - Go for it/

**Comment by jburz2001** [comment]
Sounds good. Thanks for the context, Ben.

I fixed the bug in a recent commit to the _main_ branch. I'll try to write an example that incorporates it soon.
